// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCaE3ZAJej2X3OjFm8I6DsCxj-9K_1FeM',
    appId: '1:586118557892:android:8b43d275c61a855f201991',
    messagingSenderId: '586118557892',
    projectId: 'dekeyser-d33a7',
    storageBucket: 'dekeyser-d33a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZJMyPsFdCfHeX8MotIWN1LaGFm6JaVc',
    appId: '1:586118557892:ios:c39386f337127165201991',
    messagingSenderId: '586118557892',
    projectId: 'dekeyser-d33a7',
    storageBucket: 'dekeyser-d33a7.appspot.com',
    iosClientId:
        '586118557892-k6rhbl9kdfd1lvd777b54hpjamhbbomu.apps.googleusercontent.com',
    iosBundleId: 'ch.dekeyser.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZJMyPsFdCfHeX8MotIWN1LaGFm6JaVc',
    appId: '1:586118557892:ios:c39386f337127165201991',
    messagingSenderId: '586118557892',
    projectId: 'dekeyser-d33a7',
    storageBucket: 'dekeyser-d33a7.appspot.com',
    iosClientId:
        '586118557892-k6rhbl9kdfd1lvd777b54hpjamhbbomu.apps.googleusercontent.com',
    iosBundleId: 'ch.dekeyser.myapp',
  );
}
