include: package:very_good_analysis/analysis_options.yaml


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  language:
    strict-casts: true
    strict-raw-types: false

linter:
  rules:
    prefer_function_declarations_over_variables: false
    avoid_redundant_argument_values: false
    avoid_dynamic_calls: false
    comment_references: false # don't limit commenting, even though it might indicate the code could be written better.
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: false
    lines_longer_than_80_chars: false
    prefer_asserts_with_message: false
    prefer_single_quotes: false
    public_member_api_docs: false
    omit_local_variable_types: false
    unnecessary_await_in_return: false # what if you change a function with dynamic return type from async to sync?
    unnecessary_lambdas: false # don't like this one.